{% set name = "json-merge-patch" %}
{% set version = "0.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4a022d78fc2f09cb49d96c646efc380d3b5ead2b5c7dabe22c3928c2c2e9c4e0

build:
  skip: true # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python

test:
  imports:
    - json_merge_patch
    - json_merge_patch.cli
    - json_merge_patch.lib
  commands:
    - pip check
    - pytest -v ${SP_DIR}/json_merge_patch/tests.py
  requires:
    - pip
    - pytest

about:
  home: https://github.com/OpenDataServices/json-merge-patch
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Provides functions to merge json in accordance with RFC 7386

  description: |
    json-merge-patch library provides functions to merge json in
    accordance with https://datatracker.ietf.org/doc/html/rfc7386
  doc_url: https://datatracker.ietf.org/doc/html/rfc7386
  dev_url: https://github.com/OpenDataServices/json-merge-patch

extra:
  recipe-maintainers:
    - BrentDorsey
