travis:
  secure:
    BINSTAR_TOKEN: U4L8JzR0CKsFYPBiGV6B6FAZXWD7uO7NriS7+UVXOnXb3dmsmx+lmQaNHZSgY8CY5cEfNrYO8wEbD2doBEvmEHfF403m8/mtT3qMFjAlaU+G3RJpRqnbY2H+fGzwNShK2dGnKNpL86pxf2ZYPZtlIUgzCYZaS+hfsFJKLmZHy3t3beilttmA4bwZI6UIH1/TFKPfHPa5lzLZae82Ve+NkojUzpTp59q7NVFPYsEGI/EC8ivA3i4HYPswI6T7jyci8CO+rnY3kTT0GENGCGtljdMksu7KNmh+oG2GVp+tPndXNp5gXiVeJvCDTkdtWHMlA7TJP4K4pCm3kFY50VFXixMI3//6hvb5/ynIWyifNN6y991do+MALLGYSAfyc9FDj/F7RjIPkjsldvUZ2jMtcES6wBP1Xf6jc75kaib0399YLqG4SO35QoOeNwOoSsolk/y2a4w2Jt8pSeKkQQTv7ZEY0L0O1SAspfDTwy6o6CaW9q0JVO8Q9rTN4Vfpc7NUQm5pCBrZ1csB4fm9Pq23Tbf/P7nnZO2krTsx+8YbrewKlALDTnXBEv/sOs5wE10IOyuvvo2oOq7R3Xp8j5KQO9ZRs/tCmDd4zEMjJ+NfBH8DpIn98KVyY+wESxh/MjnBjCqJNQIx1SLJFKViL55PYjmU0H03FvG6y9cPV/S5Q6A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
